load("@aspect_rules_py//py:defs.bzl", "py_test")

# Test targets for scheduler chaos test.
# Each test uses a unique TEST_ID to identify itself.

py_test(
    name = "test1",
    srcs = ["test_binary.py"],
    main = "test_binary.py",
    env = {"TEST_ID": "1"},
    deps = ["//lib:test_client"],
)

py_test(
    name = "test2",
    srcs = ["test_binary.py"],
    main = "test_binary.py",
    env = {"TEST_ID": "2"},
    deps = ["//lib:test_client"],
)

py_test(
    name = "runner",
    tags = ["local"],
    size = "large",
    timeout = "long",
    srcs = ["runner.py"],
    data = glob(["config/*.jsonnet"]) + glob(["config/*.libsonnet"]),
    env_inherit = ["HOME"],
    deps = [
        "//lib:bazel_runner",
        "//lib:message_coordination",
        "//lib:service_manager",
        "//lib:test_runner",
    ],
)
